// server/api/leads/[id]/emails.get.ts
import { defineEventHandler, createError } from 'h3'
import mongoose from 'mongoose'

export default defineEventHandler(async (event) => {
  const id = event.context.params?.id
  if (!id) {
    throw createError({ 
      statusCode: 400, 
      message: 'Lead ID is required' 
    })
  }

  try {
    // Use require to avoid TypeScript import issues
    const { connectDB } = await import('../../../utils/mongoose')
    await connectDB()
    
    // Import models using require
    const Lead = (await import('../../../models/Lead')).default
    const EmailLog = (await import('../../../models/EmailLog')).default

    // Find lead
    const lead = await Lead.findById(id).lean()
    if (!lead) {
      throw createError({ 
        statusCode: 404, 
        message: 'Lead not found' 
      })
    }

    // Fetch email logs for this lead
    const logs = await EmailLog.find({ leadId: id })
      .sort({ sentAt: -1 })
      .lean()

    // Transform the data
    const transformedLogs = logs.map((log: any) => ({
      id: log._id ? log._id.toString() : '',
      leadId: log.leadId ? log.leadId.toString() : null,
      toEmail: log.toEmail || '',
      toName: log.toName || '',
      templateId: log.templateId || null,
      subject: log.subject || '',
      previewHtml: log.previewHtml || '',
      fullHtml: log.fullHtml || '',
      params: log.params || {},
      body: log.body || {},
      sentBy: log.sentBy || null,
      autoGenerated: log.autoGenerated || false,
      status: log.status || 'sent',
      response: log.response || null,
      scheduledAt: log.scheduledAt ? new Date(log.scheduledAt).toISOString() : null,
      sentAt: log.sentAt ? new Date(log.sentAt).toISOString() : null,
      createdAt: log.createdAt ? new Date(log.createdAt).toISOString() : null,
      updatedAt: log.updatedAt ? new Date(log.updatedAt).toISOString() : null
    }))

    return transformedLogs
  } catch (error: any) {
    console.error('Failed to fetch email logs:', error)
    throw createError({ 
      statusCode: 500, 
      message: 'Failed to fetch email history' 
    })
  }
})