<template>
  <Transition name="modal">
    <div v-if="visible" class="fixed inset-0 z-50 flex items-start justify-center p-4 sm:p-6 bg-black/40">
      <div class="bg-white rounded-2xl w-full max-w-6xl shadow-xl overflow-hidden flex flex-col max-h-[90vh]">
        <!-- HEADER -->
        <div class="flex items-center justify-between px-6 py-4 border-b border-slate-200">
          <div>
            <h3 class="text-lg font-semibold text-slate-900">Email History</h3>
            <p class="text-sm text-slate-500">Emails sent to {{ leadName || 'this lead' }}</p>
          </div>
          <div class="flex items-center gap-2">
            <button 
              @click="load" 
              :disabled="loading"
              class="inline-flex items-center px-3 py-1.5 text-sm border border-slate-300 rounded-lg hover:bg-slate-50 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <svg v-if="loading" class="w-3 h-3 mr-1.5 animate-spin" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
              </svg>
              Refresh
            </button>
            <button 
              @click="close" 
              class="p-2 hover:bg-slate-100 rounded-lg transition-colors"
            >
              <svg class="w-5 h-5 text-slate-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>

        <!-- CONTENT -->
        <div class="flex flex-1 overflow-hidden">
          <!-- LEFT SIDEBAR: Email List -->
          <div class="w-1/3 border-r border-slate-200 overflow-auto bg-slate-50/50">
            <div v-if="loading && logs.length === 0" class="p-8 text-center">
              <div class="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
              <p class="text-sm text-slate-500 mt-3">Loading email history...</p>
            </div>

            <div v-else-if="logs.length === 0" class="p-8 text-center">
              <svg class="mx-auto h-12 w-12 text-slate-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M3 8l7.89 4.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
              </svg>
              <p class="mt-3 text-sm text-slate-500">No emails sent yet</p>
              <p class="text-xs text-slate-400 mt-1">All emails sent to this lead will appear here</p>
            </div>

            <ul v-else class="divide-y divide-slate-100">
              <li
                v-for="log in logs"
                :key="log.id"
                @click="selectLog(log)"
                :class="[
                  'px-4 py-3 cursor-pointer transition-colors',
                  selectedLog?.id === log.id 
                    ? 'bg-blue-50 border-r-2 border-blue-500' 
                    : 'hover:bg-slate-50'
                ]"
              >
                <div class="flex justify-between items-start">
                  <div class="flex-1 min-w-0">
                    <div class="font-medium text-sm text-slate-900 truncate">
                      {{ log.subject || `Template #${log.templateId || 'Unknown'}` }}
                    </div>
                    <div class="flex items-center gap-2 mt-1">
                      <span class="text-xs text-slate-500 truncate">{{ log.toEmail }}</span>
                      <span class="text-xs text-slate-400">•</span>
                      <span class="text-xs text-slate-500">{{ formatDateShort(log.sentAt) }}</span>
                    </div>
                  </div>
                  <div class="shrink-0 ml-2">
                    <span :class="[
                      'inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium',
                      log.status === 'sent' ? 'bg-green-100 text-green-800' :
                      log.status === 'failed' ? 'bg-red-100 text-red-800' :
                      log.status === 'scheduled' ? 'bg-yellow-100 text-yellow-800' :
                      'bg-slate-100 text-slate-800'
                    ]">
                      {{ log.status }}
                    </span>
                  </div>
                </div>
                <div class="mt-2 flex items-center justify-between">
                  <span class="text-xs text-slate-500">
                    {{ log.autoGenerated ? 'Auto-generated' : 'Manual' }}
                  </span>
                  <span v-if="log.templateId" class="text-xs text-slate-400">
                    Template #{{ log.templateId }}
                  </span>
                </div>
                <!-- HTML Availability Indicator - UPDATED TO CHECK BOTH FIELDS -->
                <div v-if="(log.fullHtml && log.fullHtml.length > 100) || (log.html && log.html.length > 100)" class="mt-1">
                  <span class="inline-flex items-center px-2 py-0.5 rounded-full text-xs bg-blue-100 text-blue-800">
                    <svg class="w-3 h-3 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    HTML Preview Available
                  </span>
                </div>
                <div v-else class="mt-1">
                  <span class="inline-flex items-center px-2 py-0.5 rounded-full text-xs bg-amber-100 text-amber-800">
                    <svg class="w-3 h-3 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.346 16.5c-.77.833.192 2.5 1.732 2.5z" />
                    </svg>
                    Text Preview Only
                  </span>
                </div>
              </li>
            </ul>
          </div>

          <!-- RIGHT PANEL: Email Details -->
          <div class="w-2/3 overflow-auto p-6">
            <div v-if="!selectedLog" class="text-center py-12">
              <svg class="mx-auto h-16 w-16 text-slate-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              <h3 class="mt-4 text-lg font-medium text-slate-900">Select an email</h3>
              <p class="mt-2 text-sm text-slate-500">Choose an email from the list to view details</p>
            </div>

            <div v-else class="space-y-6">
              <!-- EMAIL HEADER -->
              <div class="bg-slate-50 rounded-xl p-4">
                <div class="flex items-start justify-between">
                  <div class="flex-1">
                    <h4 class="text-lg font-semibold text-slate-900">
                      {{ selectedLog.subject || `Template #${selectedLog.templateId || 'Unknown'}` }}
                    </h4>
                    <div class="mt-2 space-y-1">
                      <div class="flex items-center text-sm text-slate-600">
                        <svg class="w-4 h-4 mr-2 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                        </svg>
                        <span class="truncate">To: {{ selectedLog.toName || selectedLog.toEmail }}</span>
                      </div>
                      <div class="flex items-center text-sm text-slate-600">
                        <svg class="w-4 h-4 mr-2 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                        </svg>
                        Sent: {{ formatDateLong(selectedLog.sentAt) }}
                      </div>
                    </div>
                  </div>
                  <div class="shrink-0">
                    <span :class="[
                      'inline-flex items-center px-3 py-1 rounded-full text-sm font-medium',
                      selectedLog.status === 'sent' ? 'bg-green-100 text-green-800' :
                      selectedLog.status === 'failed' ? 'bg-red-100 text-red-800' :
                      selectedLog.status === 'scheduled' ? 'bg-yellow-100 text-yellow-800' :
                      'bg-slate-100 text-slate-800'
                    ]">
                      {{ selectedLog.status }}
                    </span>
                  </div>
                </div>
              </div>

              <!-- EMAIL PREVIEW SECTION -->
              <div class="border border-slate-200 rounded-lg overflow-hidden">
                <div class="px-4 py-2 bg-slate-100 border-b border-slate-200 flex items-center justify-between">
                  <div class="text-xs font-medium text-slate-700">
                    {{ hasFullHtmlPreview(selectedLog) ? 'Email Preview' : 'Email Details' }}
                  </div>
                  <div class="flex items-center gap-2">
                    <template v-if="hasFullHtmlPreview(selectedLog)">
                      <button 
                        @click="showRawHtml = !showRawHtml"
                        class="text-xs text-slate-500 hover:text-slate-700 px-2 py-1 rounded hover:bg-slate-200"
                      >
                        {{ showRawHtml ? 'Show Preview' : 'Show HTML Code' }}
                      </button>
                      <button 
                        @click="openFullScreen"
                        class="text-xs text-slate-500 hover:text-slate-700 px-2 py-1 rounded hover:bg-slate-200"
                      >
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 8V4m0 0h4M4 4l5 5m11-1V4m0 0h-4m4 0l-5 5M4 16v4m0 0h4m-4 0l5-5m11 5v-4m0 4h-4m4 0l-5-5" />
                        </svg>
                        Full Screen
                      </button>
                    </template>
                  </div>
                </div>
                
                <!-- ACTUAL HTML EMAIL PREVIEW (IFRAME) -->
                <div v-if="hasFullHtmlPreview(selectedLog) && !showRawHtml" class="email-preview-container">
                  <!-- Email simulator header -->
                  <div class="email-simulator-header">
                    <div class="email-simulator-header-content">
                      <div class="flex items-center gap-3">
                        <div class="w-8 h-8 bg-slate-300 rounded-full"></div>
                        <div class="flex-1">
                          <div class="flex items-center justify-between">
                            <div>
                              <div class="text-sm font-medium text-slate-900">Zafs Tours</div>
                              <div class="text-xs text-slate-500">to {{ selectedLog.toName || selectedLog.toEmail }}</div>
                            </div>
                            <div class="text-xs text-slate-500">{{ formatDateLong(selectedLog.sentAt) }}</div>
                          </div>
                          <div class="mt-1">
                            <div class="text-sm font-semibold text-slate-900">{{ selectedLog.subject || 'Email from Zafs Tours' }}</div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  
                  <!-- Actual email content in iframe -->
                  <div class="email-content-wrapper">
                    <iframe 
                      :srcdoc="getFormattedEmailHtml()"
                      class="email-iframe"
                      title="Email Preview"
                      sandbox="allow-same-origin"
                    ></iframe>
                  </div>
                </div>
                
                <!-- RAW HTML VIEW -->
                <div v-if="showRawHtml && hasFullHtmlPreview(selectedLog)" class="p-4 bg-slate-50">
                  <pre class="text-xs text-slate-700 whitespace-pre-wrap wrap-break-word overflow-auto font-mono max-h-96">
{{ getEmailHtml(selectedLog) }}
                  </pre>
                </div>
                
                <!-- PREVIEW TEXT ONLY -->
                <div v-if="!hasFullHtmlPreview(selectedLog)" class="p-6 bg-white">
                  <div class="space-y-4">
                    <div v-if="selectedLog.previewHtml">
                      <h5 class="text-sm font-semibold text-slate-700 mb-2">Preview Text:</h5>
                      <p class="text-slate-600 italic p-3 bg-slate-50 rounded-lg border border-slate-200">
                        "{{ selectedLog.previewHtml }}"
                      </p>
                    </div>
                    
                    <div v-if="selectedLog.params && Object.keys(selectedLog.params).length > 0">
                      <h5 class="text-sm font-semibold text-slate-700 mb-2">Email Parameters:</h5>
                      <div class="text-xs bg-slate-50 p-4 rounded border border-slate-200">
                        <pre class="whitespace-pre-wrap">{{ pretty(selectedLog.params) }}</pre>
                      </div>
                    </div>
                    
                    <div class="p-3 bg-amber-50 border border-amber-200 rounded-lg">
                      <p class="text-xs text-amber-700">
                        <span class="font-medium">Note:</span> Full email HTML was not saved for this email. 
                        New emails sent through the system should include full HTML preview.
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              <!-- EMAIL METADATA -->
              <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                <!-- TEMPLATE INFO -->
                <div class="border border-slate-200 rounded-lg p-4">
                  <h5 class="text-sm font-semibold text-slate-700 mb-3">Template Information</h5>
                  <div class="space-y-2">
                    <div>
                      <div class="text-xs text-slate-500">Template ID</div>
                      <div class="text-sm font-medium text-slate-900">
                        {{ selectedLog.templateId || 'Not specified' }}
                      </div>
                    </div>
                    <div>
                      <div class="text-xs text-slate-500">Content Available</div>
                      <div class="text-sm font-medium">
                        <span :class="hasFullHtmlPreview(selectedLog) ? 'text-green-600' : 'text-amber-600'">
                          {{ hasFullHtmlPreview(selectedLog) ? 'Full HTML Available' : 'Preview Only' }}
                        </span>
                      </div>
                    </div>
                    <div>
                      <div class="text-xs text-slate-500">Generation Type</div>
                      <div class="text-sm font-medium text-slate-900">
                        {{ selectedLog.autoGenerated ? 'Auto-generated' : 'Manual' }}
                      </div>
                    </div>
                  </div>
                </div>

                <!-- PARAMETERS -->
                <div class="border border-slate-200 rounded-lg p-4">
                  <h5 class="text-sm font-semibold text-slate-700 mb-3">Parameters Used</h5>
                  <div class="max-h-60 overflow-y-auto">
                    <pre class="text-xs bg-slate-50 p-3 rounded-lg whitespace-pre-wrap wrap-break-word font-mono">
{{ pretty(selectedLog.params) }}
                    </pre>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </Transition>

  <!-- FULL SCREEN PREVIEW MODAL -->
  <div v-if="showFullScreen" class="fixed inset-0 z-100 bg-black/90 flex items-center justify-center p-4">
    <div class="bg-white rounded-xl w-full max-w-5xl h-[90vh] overflow-hidden flex flex-col">
      <div class="px-6 py-4 border-b border-slate-200 flex items-center justify-between">
        <div>
          <h3 class="text-lg font-semibold text-slate-900">Full Email Preview</h3>
          <p class="text-sm text-slate-500 mt-1">How the email appears in the inbox</p>
        </div>
        <div class="flex items-center gap-3">
          <button @click="closeFullScreen" class="p-2 hover:bg-slate-100 rounded-lg">
            <svg class="w-5 h-5 text-slate-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
      </div>
      <div class="flex-1 overflow-hidden bg-slate-50">
        <iframe 
          v-if="hasFullHtmlPreview(selectedLog)"
          :srcdoc="getFullScreenEmailHtml()"
          class="w-full h-full border-0"
          title="Full Email Preview"
          sandbox="allow-same-origin"
        ></iframe>
        <div v-else class="flex items-center justify-center h-full">
          <div class="text-center p-8">
            <svg class="mx-auto h-12 w-12 text-slate-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.346 16.5c-.77.833.192 2.5 1.732 2.5z" />
            </svg>
            <p class="mt-3 text-sm text-slate-500">No HTML content available</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
const props = defineProps({
  leadId: {
    type: String,
    required: true
  },
  leadName: {
    type: String,
    default: ''
  },
  visible: {
    type: Boolean,
    required: true
  }
})

const emit = defineEmits(['close'])

// Local state
const loading = ref(false)
const logs = ref<any[]>([])
const selectedLog = ref<any>(null)
const showRawHtml = ref(false)
const showFullScreen = ref(false)

// Helper functions
const pretty = (obj: any) => {
  try {
    return JSON.stringify(obj, null, 2)
  } catch {
    return String(obj)
  }
}

const formatDateShort = (iso: string | null | undefined) => {
  if (!iso) return '—'
  try {
    return new Date(iso).toLocaleString(undefined, {
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    })
  } catch {
    return iso
  }
}

const formatDateLong = (iso: string | null | undefined) => {
  if (!iso) return '—'
  try {
    return new Date(iso).toLocaleString(undefined, {
      weekday: 'short',
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    })
  } catch {
    return iso
  }
}

// NEW: Helper to check if log has full HTML preview
const hasFullHtmlPreview = (log: any) => {
  return (log?.fullHtml && log.fullHtml.length > 100) || (log?.html && log.html.length > 100)
}

// NEW: Helper to get email HTML from either field
const getEmailHtml = (log: any) => {
  return log?.fullHtml || log?.html || ''
}

// Format HTML for iframe rendering - UPDATED TO USE HELPER
const getFormattedEmailHtml = () => {
  const html = getEmailHtml(selectedLog.value)
  if (!html) return ''
  
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <style>
        body {
          margin: 0;
          padding: 0;
          background-color: #f5f5f5;
          font-family: Arial, sans-serif;
        }
        .email-container {
          max-width: 600px;
          margin: 0 auto;
          background-color: white;
        }
        /* Ensure all images are responsive */
        img {
          max-width: 100% !important;
          height: auto !important;
        }
        /* Ensure tables are responsive */
        table {
          max-width: 100% !important;
          width: 100% !important;
        }
        /* Reset any conflicting styles */
        * {
          box-sizing: border-box;
        }
      </style>
    </head>
    <body>
      <div class="email-container">
        ${html}
      </div>
    </body>
    </html>
  `
}

// Format HTML for full screen - UPDATED TO USE HELPER
const getFullScreenEmailHtml = () => {
  const html = getEmailHtml(selectedLog.value)
  if (!html) return ''
  
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <style>
        body {
          margin: 0;
          padding: 20px;
          background-color: #f5f5f5;
          font-family: Arial, sans-serif;
          display: flex;
          justify-content: center;
          align-items: center;
          min-height: 100vh;
        }
        .email-container {
          max-width: 600px;
          width: 100%;
          background-color: white;
          border-radius: 8px;
          box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
          overflow: hidden;
        }
        /* Ensure all images are responsive */
        img {
          max-width: 100% !important;
          height: auto !important;
        }
        /* Ensure tables are responsive */
        table {
          max-width: 100% !important;
          width: 100% !important;
        }
        /* Reset any conflicting styles */
        * {
          box-sizing: border-box;
        }
      </style>
    </head>
    <body>
      <div class="email-container">
        ${html}
      </div>
    </body>
    </html>
  `
}

// Full screen preview
const openFullScreen = () => {
  if (hasFullHtmlPreview(selectedLog.value)) {
    showFullScreen.value = true
  }
}

const closeFullScreen = () => {
  showFullScreen.value = false
}

// Actions
const selectLog = (log: any) => {
  selectedLog.value = log
  showRawHtml.value = false
  
  // Debug
  console.log('Selected Log:', {
    id: log.id,
    hasFullHtml: log.fullHtml && log.fullHtml.length > 100,
    hasHtml: log.html && log.html.length > 100,
    fullHtmlLength: log.fullHtml?.length || 0,
    htmlLength: log.html?.length || 0,
    previewHtml: log.previewHtml
  })
}

const load = async () => {
  if (!props.leadId) return
  
  loading.value = true
  try {
    console.log('🔍 Loading email logs for lead:', props.leadId)
    
    // FIRST: Get the lead details to get the email
    let leadEmail = ''
    try {
      const leadDetails: any = await $fetch(`/api/leads/${props.leadId}`)
      leadEmail = leadDetails?.email
      console.log('📧 Lead email found:', leadEmail)
    } catch (leadError) {
      console.error('❌ Failed to fetch lead details:', leadError)
    }
    
    // Try multiple approaches to find email logs
    
    // APPROACH 1: Direct lead endpoint (for lead-specific emails)
    try {
      console.log('🔄 Trying lead-specific endpoint...')
      const leadResponse = await $fetch(`/api/leads/${props.leadId}/emails`)
      if (Array.isArray(leadResponse) && leadResponse.length > 0) {
        logs.value = leadResponse
        console.log(`✅ Found ${logs.value.length} emails via lead endpoint`)
        if (logs.value.length > 0) {
          selectLog(logs.value[0])
        }
        loading.value = false
        return
      }
    } catch (error) {
      console.log('📭 Lead-specific endpoint returned no emails or failed:', error)
    }
    
    // APPROACH 2: General log endpoint with leadId
    console.log('🔄 Trying general log endpoint with leadId...')
    const response: any = await $fetch('/api/emailtest/log', {
      params: { 
        leadId: props.leadId,
        limit: 100 // Get more logs
      }
    })
    
    console.log('📋 General log response:', response)
    
    if (response?.success && response?.data?.logs) {
      logs.value = response.data.logs
      console.log(`✅ Found ${logs.value.length} emails via general endpoint`)
      
      // Debug: check each log
      logs.value.forEach((log, index) => {
        console.log(`📝 Log ${index + 1}:`, {
          id: log.id,
          leadId: log.leadId,
          hasLeadId: !!log.leadId,
          subject: log.subject,
          templateId: log.templateId
        })
      })
      
      if (logs.value.length > 0) {
        selectLog(logs.value[0])
      }
    } else if (leadEmail) {
      // APPROACH 3: If no logs found by leadId, try by email
      console.log(`🔄 No logs found by leadId, trying by email: ${leadEmail}`)
      const emailResponse: any = await $fetch('/api/emailtest/log', {
        params: { 
          email: leadEmail,
          limit: 100
        }
      })
      
      if (emailResponse?.success && emailResponse?.data?.logs) {
        logs.value = emailResponse.data.logs
        console.log(`✅ Found ${logs.value.length} emails via email search`)
        
        if (logs.value.length > 0) {
          selectLog(logs.value[0])
        }
      }
    }
    
    if (logs.value.length === 0) {
      console.log('📭 No email logs found for this lead')
    }
    
  } catch (error) {
    console.error('❌ Error loading email logs:', error)
  } finally {
    loading.value = false
  }
}


const close = () => {
  showRawHtml.value = false
  showFullScreen.value = false
  emit('close')
}

// Watch for visibility changes
watch(() => props.visible, (val) => {
  if (val && props.leadId) {
    load()
  }
})

watch(() => props.leadId, (val) => {
  if (val && props.visible) {
    load()
  }
})
</script>

<style scoped>
.modal-enter-active,
.modal-leave-active {
  transition: opacity 0.2s ease;
}

.modal-enter-from,
.modal-leave-to {
  opacity: 0;
}

/* Email preview container */
.email-preview-container {
  background-color: #f5f5f5;
  border-radius: 0 0 8px 8px;
  overflow: hidden;
}

/* Email simulator header */
.email-simulator-header {
  background: linear-gradient(to bottom, #f8f9fa, #e9ecef);
  border-bottom: 1px solid #dee2e6;
  padding: 12px 16px;
}

.email-simulator-header-content {
  max-width: 600px;
  margin: 0 auto;
}

/* Email content wrapper */
.email-content-wrapper {
  background-color: #f5f5f5;
  padding: 20px;
  min-height: 400px;
  display: flex;
  justify-content: center;
}

/* Email iframe for proper rendering */
.email-iframe {
  width: 100%;
  max-width: 600px;
  height: 500px;
  border: none;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  background-color: white;
}

/* Scrollbar styling */
.email-iframe::-webkit-scrollbar {
  width: 6px;
}

.email-iframe::-webkit-scrollbar-track {
  background: #f1f5f9;
}

.email-iframe::-webkit-scrollbar-thumb {
  background: #cbd5e1;
  border-radius: 3px;
}

.email-iframe::-webkit-scrollbar-thumb:hover {
  background: #94a3b8;
}

/* Full screen preview */
.fullscreen-iframe {
  width: 100%;
  height: 100%;
  border: none;
}
</style>