// server/models/EmailLog.ts
import mongoose from 'mongoose'

const EmailLogSchema = new mongoose.Schema({
  leadId: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'Lead', 
    index: true 
  },
  toEmail: { type: String, required: true },
  toName: { type: String, default: '' },
  templateId: { type: Number, default: null },
  subject: { type: String, default: '' },
  previewHtml: { type: String, default: '' },
  fullHtml: { type: String, default: '' }, // NEW FIELD: Complete rendered email HTML
  params: { type: Object, default: {} },
  body: { type: Object, default: {} },
  sentBy: {
    id: { type: String, default: null },
    name: { type: String, default: '' },
    email: { type: String, default: '' },
    role: { type: String, default: '' },
    source: { type: String, default: 'manual' }
  },
  autoGenerated: { type: Boolean, default: false },
  status: { 
    type: String, 
    enum: ['sent', 'failed', 'scheduled', 'delivered', 'opened', 'clicked'],
    default: 'sent' 
  },
  response: { type: Object, default: null },
  scheduledAt: { type: Date, default: null },
  sentAt: { type: Date, default: null }
}, {
  timestamps: true
})

export default mongoose.models.EmailLog || mongoose.model('EmailLog', EmailLogSchema)