// server/utils/logEmail.ts
export async function logEmail(opts: any) {
  try {
    // Connect to database
    const { connectDB } = await import('./mongoose')
    await connectDB()
    
    // Import EmailLog model
    const EmailLog = (await import('../models/EmailLog')).default
    
    const doc = {
      leadId: opts.leadId || null,
      toEmail: opts.toEmail || '',
      toName: opts.toName || '',
      templateId: opts.templateId || null,
      subject: opts.subject || '',
      previewHtml: opts.previewHtml || opts.previewText || '',
      fullHtml: opts.fullHtml || '', // NEW: Store full HTML
      body: opts.body || {},
      params: opts.params || {},
      sentBy: opts.sentBy || null,
      autoGenerated: opts.autoGenerated || false,
      status: opts.status || 'sent',
      response: opts.response || null,
      scheduledAt: opts.scheduledAt ? new Date(opts.scheduledAt) : null,
      sentAt: opts.sentAt ? new Date(opts.sentAt) : new Date()
    }

    console.log('Saving email log with full HTML:', doc.fullHtml ? 'YES' : 'NO', 'Length:', doc.fullHtml?.length || 0)
    
    const created = await EmailLog.create(doc)
    return created
  } catch (error) {
    console.error('Failed to log email:', error)
    // Don't throw - email logging shouldn't break the main flow
    return null
  }
}