// server/api/emailtest/log.get.ts - COMPLETE FIXED VERSION
import { defineEventHandler, getQuery } from 'h3'

export default defineEventHandler(async (event) => {
  try {
    // Connect to database
    const { connectDB } = await import('../../utils/mongoose')
    await connectDB()
    
    // Import EmailLog model
    const EmailLog = (await import('../../models/EmailLog')).default
    
    // Get query parameters
    const query = getQuery(event)
    const leadId = query.leadId as string
    const email = query.email as string
    const limit = parseInt(query.limit as string) || 50
    const page = parseInt(query.page as string) || 1
    const skip = (page - 1) * limit
    
    console.log('🔍 Email log search query:', { leadId, email, limit, page })
    
    // Build filter - MORE FLEXIBLE SEARCH
    const filter: any = {}
    
    if (leadId) {
      // Try to find by leadId OR by email if leadId is null (for legacy emails)
      if (email) {
        // If we have both leadId and email, search for either
        filter.$or = [
          { leadId: leadId },
          { toEmail: email, leadId: { $exists: false } },
          { toEmail: email, leadId: null }
        ]
      } else {
        // If only leadId, search for that leadId
        filter.leadId = leadId
      }
    } else if (email) {
      // If only email provided, search by email
      filter.toEmail = email
    } else {
      // If no parameters, return all logs (with limit)
      // This might be useful for admin views
    }
    
    console.log('🔍 Email log filter:', JSON.stringify(filter, null, 2))
    
    // Get logs with pagination
    const [logs, total] = await Promise.all([
      EmailLog.find(filter)
        .sort({ sentAt: -1 })
        .skip(skip)
        .limit(limit)
        .lean(),
      EmailLog.countDocuments(filter)
    ])
    
    console.log(`📊 Found ${logs.length} email logs out of ${total} total`)
    
    // Transform the data
    const transformedLogs = logs.map((log: any) => ({
      id: log._id ? log._id.toString() : '',
      leadId: log.leadId ? log.leadId.toString() : null,
      toEmail: log.toEmail || '',
      toName: log.toName || '',
      templateId: log.templateId || null,
      subject: log.subject || '',
      previewHtml: log.previewHtml || '',
      fullHtml: log.fullHtml || '',
      html: log.html || '',
      params: log.params || {},
      body: log.body || {},
      sentBy: log.sentBy || null,
      autoGenerated: log.autoGenerated || false,
      status: log.status || 'sent',
      response: log.response || null,
      scheduledAt: log.scheduledAt ? new Date(log.scheduledAt).toISOString() : null,
      sentAt: log.sentAt ? new Date(log.sentAt).toISOString() : null,
      createdAt: log.createdAt ? new Date(log.createdAt).toISOString() : null,
      updatedAt: log.updatedAt ? new Date(log.updatedAt).toISOString() : null
    }))
    
    return {
      success: true,
      data: {
        logs: transformedLogs,
        pagination: {
          total,
          page,
          limit,
          pages: Math.ceil(total / limit)
        }
      }
    }
  } catch (error: any) {
    console.error('❌ Failed to fetch email logs:', error)
    return {
      success: false,
      message: 'Failed to fetch email logs',
      error: error.message
    }
  }
})