// app/types/email.d.ts
export interface EmailLog {
  id: string
  leadId: string
  toEmail: string
  toName: string
  templateId: number | null
  subject: string
  previewHtml: string
  fullHtml: string  // NEW: Full rendered email HTML
  params: Record<string, any>
  body: Record<string, any>
  sentBy: {
    id?: string
    name?: string
    email?: string
    role?: string
    source?: string
  } | null
  autoGenerated: boolean
  status: 'sent' | 'failed' | 'scheduled' | 'delivered' | 'opened' | 'clicked'
  response: Record<string, any> | null
  scheduledAt: string | null
  sentAt: string | null
  createdAt: string
  updatedAt: string
}